test de pipeline  modificaiton car soucis avec le .env

diff --git a/.github/workflows/launch_test.yml b/.github/workflows/launch_test.yml
--- a/.github/workflows/launch_test.yml
+++ b/.github/workflows/launch_test.yml
@@ -24,17 +24,24 @@ jobs:
       - name: Install Dependencies
         run: flutter pub get
 
+      - name: Ensure .env exists
+        run: |
+          if [ ! -f .env ]; then
+            echo ".env file missing, creating from .env.example"
+            cp .env.example .env
+          fi
+
       - name: Run Flutter Tests
         run: flutter test --coverage
 
       - name: Fix Slashes in Coverage File
-        run: sed -i 's|\\|/|g' coverage/lcov-report/lcov.info
+        run: sed -i 's|\\|/|g' coverage/lcov-report/lcov.info || true
 
       - name: Generate Coverage HTML Report
-        run: genhtml coverage/lcov-report/lcov.info -o coverage/html
+        run: genhtml coverage/lcov-report/lcov.info -o coverage/html || true
 
       - name: Upload Coverage Report
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@v3
         with:
           name: coverage-report
           path: coverage/html
